### ISSUE TITLE
Balancing regarding Mysterious Vial

### ISSUE THREAD

**Issue by Crypto-Spartan** [DestroyedClone/RiskyClassicItems#4]
Hi, I'm a big fan of this mod, thanks for making & maintaining it!

Based on the stats for [Titanic Knurl](https://riskofrain2.fandom.com/wiki/Titanic_Knurl), it seems that Mysterious Vial might be a bit overtuned for RoR2. Knurl is a Boss rarity item, and it only increases health regen by 1.6hp/s. I know that Mysterious Vial increases regen by 1hp/s which is less, but it still seems like a lot for a white item.

You may completely disagree with me, and I would understand. It just seems that Vial would be a bit too weak to be a green item but it's a bit too strong to be a white item. I'm thinking maybe a small nerf to 0.8 hp/s so that each stack is half of a Knurl.

**Comment by Moffein** [comment]
I appreciate the feedback!
I think Mysterious Vial is in a good spot currently. While its regen is close to Knurl's, Knurl is generally regarded as the weakest boss item in the game due to its overall very low stats. Compared to other white items, Slug is more practical for saving you from low health and cheesing blood shrines, and Weeping Fungus's raw passive healing is just outright way higher. Even Starstorm's Dormant Fungus (Weeping Fungus but with around half of the healing) outpaces Vial at Level 1.

Overall, I see Vial as an item that's nice to have and can be useful when stacked, but not outright run defining where you'd go out of your way to print it.

**Comment by Crypto-Spartan** [comment]
fair points, thanks for the consideration
